### ISSUE TITLE
Allow dynamic linking

### ISSUE THREAD

**Issue by PureTryOut** [MayaPosch/NymphRPC#4]
Linux Distributions don't like statically compiled packages. It forces rebuilds of all packages when the static library gets updated even when the ABI hasn't changed, the package sizes get bigger, etc. Currently libnymphrpc gets compiled as a static library (`.a`), but it would be great if it could be linked too dynamically (as a `.so` file).

**Comment by MayaPosch** [comment]
Feature has been implemented. Please see whether it works for you.

**Comment by PureTryOut** [comment]
Thanks. However, nymphcast (latest commit as of writing this comment) can't find the library. I installed it to `/usr/lib/libnymphrpc.so`.

**Comment by PureTryOut** [comment]
Works, thanks!
